########################################################################################
# "pnpm install" composite action                                                  #
#--------------------------------------------------------------------------------------#
# Cache:                                                                               #
#   - pnpm store                                                                       #
#   - node_modules directory                                                           #
########################################################################################

name: 'pnpm install'
description: 'Run pnpm install --frozen-lockfile with cache enabled'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: false
    default: v22.x

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.15.0

    - name: Use Node ${{ inputs.node_version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node_version }}
        cache: pnpm

    # Cache node_modules
    - name: Restore node_modules
      id: nm-cache
      uses: actions/cache@v5
      with:
        path: '**/node_modules/'
        key: ${{ runner.os }}-pnpm-nm-cache-${{ hashFiles('pnpm-lock.yaml', 'package.json') }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate Prisma client
      shell: bash
      working-directory: packages/db
      run: pnpm run db:generate
